{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torchvision.models as models"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class FeatureExtraction(torch.nn.Module):\n",
    "    def __init__(self, use_cuda =True, feature_extraction_cnn ='vgg', last_layer=''):\n",
    "        super(FeatureExtraction, self).__init__()\n",
    "        self.model = models.vgg16(pretrained=True)\n",
    "        vgg_feature_layers = ['conv1_1', 'relu1_1', 'conv1_2', 'relu1_2', 'pool1',\n",
    "                                  'conv2_1', 'relu2_1', 'conv2_2', 'relu2_2', 'pool2',\n",
    "                                  'conv3_1', 'relu3_1', 'conv3_2', 'relu3_2', 'conv3_3',\n",
    "                                  'relu3_3', 'pool3', 'conv4_1', 'relu4_1', 'conv4_2',\n",
    "                                  'relu4_2', 'conv4_3', 'relu4_3', 'pool4', 'conv5_1',\n",
    "                                  'relu5_1', 'conv5_2', 'relu5_2', 'conv5_3', 'relu5_3', 'pool5']\n",
    "        if last_tear == '':\n",
    "            last_layer = 'pool4'\n",
    "        last_year_idx = vgg_feature_layers.index(last_layer)\n",
    "        \n",
    "        self.model = nn.Sequential(*list(self.model.features.children())\n",
    "                                  [:last_layer_idx+1])\n",
    "        \n",
    "        # freeze parameters\n",
    "        for param in self.model.parameters():\n",
    "            param.requires_grad = False\n",
    "        \n",
    "        if use_cuda:\n",
    "            self.model.cuda()\n",
    "            \n",
    "    def forward(self, img_batch):\n",
    "        image_batch = image_batch.cuda()\n",
    "        return self.model(image_batch)\n",
    "        \n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "class FeatureL2Norm(torch.nn.Module):\n",
    "    def __init__(self):\n",
    "        super(FeatureL2Norm, self).__init__()\n",
    "\n",
    "    def forward(self, feature):\n",
    "        epsilon = 1e-6\n",
    "        norm = torch.pow(torch.sum(torch.pow(feature, 2),\n",
    "                                   1)+epsilon,\n",
    "                         0.5).unsqueeze(1).expand_as(feature)\n",
    "\n",
    "        return torch.div(feature, norm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "class FeatureCorrelation(torch.nn.Module):\n",
    "    def __init__(self):\n",
    "        super(FeatureCorrelation, self).__init__()\n",
    "\n",
    "    def forward(self, feature_A, feature_B):\n",
    "\n",
    "        b, c, h, w = feature_A.size()\n",
    "\n",
    "        # reshape features for matrix multiplication\n",
    "        feature_A = feature_A.transpose(2, 3).contiguous().view(b, c, h*w)\n",
    "        feature_B = feature_B.view(b, c, h*w).transpose(1, 2)\n",
    "\n",
    "        # perform matrix multiplication\n",
    "        feature_mul = torch.bmm(feature_B, feature_A)\n",
    "        correlation_tensor = feature_mul.view(b, h,\n",
    "                                              w, h*w).transpose(2, 3).transpose(1, 2)\n",
    "\n",
    "        return correlation_tensor.to(device=\"cuda\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "class FeatureRegression(nn.Module):\n",
    "    def __init__(self, output_dim=6, use_cuda=True):\n",
    "        super(FeatureRegression, self).__init__()\n",
    "        self.conv = nn.Sequential(\n",
    "            nn.Conv2d(225, 128, kernel_size=7, padding=0),\n",
    "            nn.BatchNorm2d(128),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(128, 64, kernel_size=5, padding=0),\n",
    "            nn.BatchNorm2d(64),\n",
    "            nn.ReLU(inplace=True),\n",
    "        )\n",
    "        self.linear = nn.Linear(64 * 5 * 5, output_dim)\n",
    "        if use_cuda:\n",
    "            self.conv.cuda()\n",
    "            self.linear.cuda()\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.conv(x)\n",
    "        x = x.view(x.size(0), -1)\n",
    "        x = self.linear(x)\n",
    "        return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "class CNNGeometric(nn.Module):\n",
    "    def __init__(self, normalize_features=True, normalize_matches=True,\n",
    "                 use_cuda=True, feature_extraction_cnn='vgg'):\n",
    "\n",
    "        super(CNNGeometric, self).__init__()\n",
    "        self.use_cuda = use_cuda\n",
    "        self.normalize_features = normalize_features\n",
    "        self.normalize_matches = normalize_matches\n",
    "\n",
    "        self.FeatureExtraction = FeatureExtraction(use_cuda=self.use_cuda,\n",
    "                                                   feature_extraction_cnn=feature_extraction_cnn)\n",
    "\n",
    "        self.FeatureL2Norm = FeatureL2Norm()\n",
    "        self.FeatureCorrelation = FeatureCorrelation()\n",
    "        \n",
    "        output_dim = 6\n",
    "\n",
    "        self.FeatureRegression = FeatureRegression(output_dim,\n",
    "                                                   use_cuda=self.use_cuda)\n",
    "        self.ReLU = nn.ReLU(inplace=True)\n",
    "\n",
    "    def forward(self, tnf_batch):\n",
    "        #print('cnn_geometric_model.py: do feature extraction')\n",
    "        # do feature extraction\n",
    "        feature_A = self.FeatureExtraction(tnf_batch['source_image'])\n",
    "        #print('cnn_geometric_model.py: feature_A')\n",
    "        feature_B = self.FeatureExtraction(tnf_batch['target_image'])\n",
    "        # normalize\n",
    "        #print('cnn_geometric_model.py: normalize')\n",
    "        if self.normalize_features:\n",
    "            feature_A = self.FeatureL2Norm(feature_A)\n",
    "            feature_B = self.FeatureL2Norm(feature_B)\n",
    "        # do feature correlation\n",
    "        correlation = self.FeatureCorrelation(feature_A, feature_B)\n",
    "        # normalize\n",
    "        if self.normalize_matches:\n",
    "            correlation = self.FeatureL2Norm(self.ReLU(correlation))\n",
    "\n",
    "        # do regression to tnf parameters theta\n",
    "        theta = self.FeatureRegression(correlation)\n",
    "\n",
    "        return theta\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
